name: ci

on: push

jobs:
  test:
    name: test create-deno-plugin on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: denolib/setup-deno@v1.2.0
        with:
          deno-version: 0.41.0
      - name: run the tool
        run: deno --allow-env --allow-read --allow-write ./main.ts ./da/plug
      - name: run a check on unix
        if: startsWith(matrix.os, 'win') == false
        run: |
          (ls \
            ./da/plug/.gitignore \
            ./da/plug/Cargo.toml \
            ./da/plug/src/lib.rs \
            ./da/plug/mod.ts && \
          exit 0) \
          || \
          exit 1
      - name: run a check on windows
        if: startsWith(matrix.os, 'win')
        run: |
          if not exist ./da/plug/.gitignore exit 1
          if not exist ./da/plug/Cargo.toml exit 1
          if not exist ./da/plug/src/lib.rs exit 1
          if not exist ./da/plug/mod.ts exit 1